language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
    only:
        - master
notifications:
  email: false
node_js:
  - v9
  - v8
  - v6
  - v4
before_script:
  - npm prune
after_success:
  - npm run semantic-release
